services:
  ctf:
    container_name: ctf
    build: .
    ports:
      - "3000:3000"
    environment:
      - ADMIN_USER=admin
      - ADMIN_PASS=ultrageheim01!
      - DB_PATH=/data/app.db
      - PORT=3000
    volumes:
      - ctf-data:/data
    restart: unless-stopped

volumes:
  ctf-data:
